replicaCount: 2

image:
  repository: helloapp
  tag: ""
  pullPolicy: IfNotPresent

imagePullSecrets: []

service:
  type: ClusterIP
  port: 80

resources:
  requests:
    cpu: 50m
    memory: 96Mi
  limits:
    memory: 192Mi
